version: '3.5'

services:

  haproxy:
    image: haproxy:2.2
    restart: always
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg
    ports: 
      - 13306:13306
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
